server:
  port: 8080

spring:
  application:
    name: SocialLoginWeb-Project
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  sql:
    init:
      mode: always #초기 구동시 스크립트 실행
  datasource:
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        oracle:
          jdbc:
            timezoneAsRegion: false
  jpa:
    hibernate:
      ddl-auto: update # 테이블 생성 또는 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_SOCIAL_ID}
            client-secret: ${GOOGLE_SOCIAL_SECRET}
            scope: profile, email
          naver:
            client-id: ${NAVER_SOCIAL_ID}
            client-secret: ${NAVER_SOCIAL_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: naver
          kakao:
            client-id: ${KAKAO_SOCIAL_ID}
            client-secret: ${KAKAO_SOCIAL_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/kakao'
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao
          github:
            client-id: ${GIT_SOCIAL_ID}
            client-secret: ${GIT_SOCIAL_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/github'
            scope: read:user,user:email
            client-name: Github
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

logging:
  level:
    com.loginSample: INFO